### ISSUE TITLE
master-master mode

### ISSUE THREAD

**Issue by kostja** [tarantool/expirationd#10]
Currently expirationd doesn't work if it detects that it's running on a slave. This is obsolete, since the server can be in master-master replication mode. Either it should check for something else (i.e. find out whether or not the instance it's currently running on is in read-only mode), or there should be an explicit flag to make sure expirationd works fine in master-master mode.

**Comment by bigbes** [comment]
Needs discussion - e.g. for N nodes in master-master we'll have duplicate packages between every node (traffic will increase in ~ N times) and all deletes will be N-dupped in xlogs, so they'll grow much faster.
It's not obvious what to do at this time.

**Comment by rtsisyk** [comment]
`force` option is enough solution.
