### ISSUE TITLE
Does not work with sophia tree multipart index

### ISSUE THREAD

**Issue by man0xff** [tarantool/expirationd#11]
2016-04-26 18:52:57.818 [10669] main/503/garage_infos_expiration sophia_index.cc:740 E> ER_UNSUPPORTED_INDEX_FEATURE: Index 'user_id_sid_rand' (TREE) of space 'garage_infos' (sophia) does not support partial keys

Space configuration:

    local s = box.schema.create_space('sample_space', {                     
        engine = 'sophia',                                                  
        if_not_exists = true,                                               
    })                                                                      
    s:create_index('sample_index', {                                    
        type = 'tree',                                                      
        parts = {1, 'num', 2, 'str'},
        if_not_exists = true,                                               
    })

**Comment by bigbes** [comment]
Fixed in latest master
