### ISSUE TITLE
Wrong example in example.lua

### ISSUE THREAD

**Issue by cerevra** [tarantool/expirationd#17]
Hi!
Example is not workable:
```
expirationd.start(job_name, space.id, is_expired, {
    process_expired_tuple = delete_tuple, args = nil,
    tuple_per_item = 50, full_scan_time = 3600
})
```

Workable:
```expirationd.run_task(job_name, space.id, is_expired, delete_tuple, nil, 50, 3600)```

May be lua experience is too small, but how this must work? Set of params are different
https://github.com/tarantool/expirationd/blob/master/expirationd.lua#L431
https://github.com/tarantool/expirationd/blob/master/expirationd.lua#L341
https://github.com/tarantool/expirationd/blob/master/expirationd.lua#L349

**Comment by bigbes** [comment]
@cerevra `run_task` is an old (obsolete) syntax for expirationd. What's wrong with `start` function?

**Comment by bigbes** [comment]
https://github.com/tarantool/expirationd/blob/094c257ccdb62f9045d409eeec587de5e69e3afb/expirationd.lua#L264

**Comment by cerevra** [comment]
Oh, sorry. I didn't noticed that in README.md ```start```

There is almost the same code in /etc/tarantool/instances.available/example.lua from deb package tarantool-common:
```
-------------------
-- Data expiration
-------------------
-- N.B. you need to install tarantool-expirationd package to use expirationd
-- Docs: https://github.com/tarantool/expirationd/blob/master/README.md
-- Example:
--job_name = 'clean_all'
--expirationd = require('expirationd')
--function is_expired(args, tuple)
--  return true
--end
--function delete_tuple(space_id, args, tuple)
--  box.space[space_id]:delete{tuple[1]}
--end
--expirationd.run_task(job_name, space.id, is_expired, {
--    process_expired_tuple = delete_tuple, args = nil,
--    tuple_per_item = 50, full_scan_time = 3600
--})
```
So I tried to use this example. Probably it should be corrected

**Comment by bigbes** [comment]
You're right. Thank you for your report. Moving ticket to https://github.com/tarantool/tarantool/issues/1877

**Comment by bigbes** [comment]
Thank you, we will fix `example.lua`.

With best regards, Eugene.

2016-10-26 23:52 GMT+03:00 Igor Klevanets <notifications@github.com>:
