### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by cerevra** [tarantool/expirationd#18]
Hi!

I found deb package on Ubuntu trusty with version=1.0.0-6
But in this project I see only 1.0.0-1

```
$ apt-cache policy tarantool-expirationd 
tarantool-expirationd:
  Installed: 1.0.0-6
  Candidate: 1.0.0-6
  Version table:
 *** 1.0.0-6 0
        500 http://download.tarantool.org/tarantool/1.7/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

Is this repo alive?

**Comment by bigbes** [comment]
Sorry for long response, everything should be fixed now. Every package should be uploaded to Ubuntu `trusty` and all three repositories
