### ISSUE TITLE
expirationd.lua:173: fiber name is too long

### ISSUE THREAD

**Issue by pjao** [tarantool/expirationd#23]
Fix was made with (https://github.com/tarantool/expirationd/commit/ff32f24c994ae8ddee1a2169c2767173ccb4654e) but still not available in the package build (Last version tarantool-expirationd/jessie,jessie,now 1.0.15-1)

Can you see what's up? @bigbes ?

**Comment by bigbes** [comment]
@pjao there were some problems with [travis-ci](https://travis-ci.org/tarantool/expirationd/builds/277346601) - package is building right now. Can you check build status in 10-30 minutes?

As I've read [here](https://www.traviscistatus.com/) - work of travis is unstable right now

**Comment by pjao** [comment]
Thanks! 

Version 1.0.16-1 is available, closing the issue!
