### ISSUE TITLE
Calling expirationd.update() creates orphaned tasks

### ISSUE THREAD

**Issue by viciious** [tarantool/expirationd#24]
https://github.com/tarantool/expirationd/blob/master/expirationd.lua#L452

```lua
    local function expirationd_update()
    local expd_prev = require('expirationd')
    package.loaded['expirationd'] = nil
    local expd_new  = require('expirationd')
    for name, task in pairs(task_list) do
        task:kill()
        expd_new.start(
                task.name, task.space_id,
```

The function should probably call stop() instead of kill(), otherwise it gets removed from the task list and the newly started task instance is orphaned: calling expd_new.start(task.name again will create more identical fibers.

**Comment by bigbes** [comment]
Closed with https://github.com/tarantool/expirationd/commit/bbc9b3994494d5c4a34f6cd45dc0c636be9ea55b.
1) iterate one dictionary of tasks and do not delete from it
2) old expirationd module contents are rewritten with the new content
