### ISSUE TITLE
Debian package build for ubuntu:bionic fails

### ISSUE THREAD

**Issue by SudoBobo** [tarantool/expirationd#32]
See travis: https://travis-ci.org/tarantool/expirationd/jobs/395023179#L616

**Comment by Totktonada** [comment]
Ubuntu Bionic was added in https://github.com/tarantool/expirationd/commit/98c5f09abe98705587204e1fd8b7406e67dc6715 . Travis CI jobs now use 1_10 tarantool repository for dependencies instead of 1_7 and it seems the problem gone.
