### ISSUE TITLE
Updated tuples deleted by expirationd

### ISSUE THREAD

**Issue by vasilky3** [tarantool/expirationd#34]
### Problem
expirationd removes not expired tuples. 

### Details
The expirationd is set like shown below
` local subs_space = box.schema.space.create('sp', {engine = "memtx"})`
`subs_space:create_index('primary', { type = "tree", parts = { 1, "string", 2, "string" } })`
` expirationd.start("sp_remove_deleted", box.space.sp.id, expire_func, { tuples_per_iteration=100, force=true, full_scan_time=2*60*60 })`

Then the expd_fiber meets api(main)_fiber we lose updated tuples. 
Looks like expd reads 100 tuples and suspends. Meanwhile Api updates tuples in DB. 
Then expd calls expire_func with outdated tuples (wich was stored in cash before suspend). This leads to errors. 

https://github.com/tarantool/expirationd/blob/7da3b43320b8b34784eac95601819db49db3f41e/expirationd.lua#L97

It seem like we can call suspend before select. But will it totally fix the problem? 
It may help if fiber won't be interrupted. 
tatantool "Fibers manager" switch fibers on any service call(e.g. select) or only by fiber.sleep()?

**Comment by bigbes** [comment]
Overwriting `process_expired_tuple` will be one of solutions: you can check that tuple is still expired, before deletion, for example.

**Comment by vasilky3** [comment]
Thanks for reply.
I already fix the problem using crdt mechanism realised in `before_replace()`.
If I'll use `process_expired_tuple` will tarantool guarantees no fiber switches between `select()` and `upsert()`?

**Comment by bigbes** [comment]
I guess it's something, that's [described](https://tarantool.io/en/doc/1.9/book/box/atomic/) in documentation: select request doesn't yield on memtx.

**Comment by vasilky3** [comment]
Thanks!
