### ISSUE TITLE
expirationd not doing anything

### ISSUE THREAD

**Issue by seet61** [tarantool/expirationd#36]
I try to use expirationd at my tarantool instance.
I add this code to my lua file:
`local function is_expired(args, tuple)
    -- logic for check
    local x = os.time()
    log.debug("check: " .. tuple[1] .. " " .. tuple[3] .. " " .. x)
    if (tuple[3] <= x) or (tuple[4] <= x) then
        return true
    else
        return false
    end
end

local function  delete_tuple(space_id, args, tuple)
    log.debug("delete from: " .. space_id .. " " .. tuple[1])
    box.space[space_id]:delete{tuple[1]}
end

for k, v in pairs(config.ttl_spaces) do
    log.debug("ttl_space: " .. v .. " " .. type(delete_tuple))
    expirationd.start(job_clean .. v, box.space[v].id, is_expired, {
        process_expired_tuple =  delete_tuple, args = nil,
        tuples_per_iteration = 500, full_scan_time = 60
    })
    expirationd.update()
    log.debug(job_clean .. v .. " was started")
end`

After that restart instance, but nothing happend. 
At stats I see that not any raw was checked:

tarantuldb-tst1:3301> expirationd.stats('clean_getDictionaries')

- expired_count: 0
  working_time: 433
  restarts: 1
  checked_count: 0
...

tarantuldb-tst1:3301> expirationd.stats('clean_getDictionaries')

- expired_count: 0
  working_time: 500
  restarts: 1
  checked_count: 0
...

Why?

**Comment by bigbes** [comment]
please, format code.
replication?

**Comment by seet61** [comment]
Yes, master - N slave

**Comment by bigbes** [comment]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/495636/52325147-0e96c900-29f5-11e9-8c28-38bab15c1923.png">

**Comment by seet61** [comment]
I tried. That didn't help.
And 
root@tarantuldb-tst1:/var# tarantool -V
Tarantool 1.10.2-111-gb4e69616a
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-1.10.2.111=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-1.10.2.111=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-cast-function-type

**Comment by bigbes** [comment]
I don't know how you tried, I can't see `force` in your configuration. Please, show me code with `force` that doesn't work.

This is definitely configuration problem, can you join `@tarantool_ru` chat in telegram and ask for help there?

ps: use quotes for code/info formatting. please.

**Comment by bigbes** [comment]
Closing issue as stale. Please, feel free to re-open it in case you have other questions.

**Comment by greatt169** [comment]
@bigbes thx! you've just saved my second day!
