### ISSUE TITLE
Refine master-master mode support

### ISSUE THREAD

**Issue by Totktonada** [tarantool/expirationd#42]
Initially the module leant on `box.cfg.replication_source` (`box.cfg.replication` for tarantool-1.7.6+) to don't start task processing on a replica. Here the word `replica` means an instance with at least one configured upstream.

Then something in the world changes and it becomes usual to use bidirectional replication with tarantool. Most of times it is not a real master-master: all writes are going to a single instance at given moment of the time. But it allows to skip replication reconfiguration step when switching an instance that aimed to process writes. This way decreases a time for the switching and decreases probability of mistakes during replica set reconfiguration. `box.cfg{read_only = true|false}` is often used to protect instances, where writes should not be performed.

In this confguration the expirationd module should process tasks only on the writeable instance and so checking of a `box.cfg.replication` is not sufficient. The option `force` [was added](https://github.com/tarantool/expirationd/issues/10) with this idea in the mind. It let a user control where to start task processing and where don't. However it obligates an application developer to externally stop tasks processing on an instance that goes to read-only and start it on an instance that goes to be writeable. It is [not quite obvious](https://github.com/tarantool/expirationd/issues/14).

This ideal solution would be ability to configure expirationd to obtain information about an instance state. Say, 'stop processing when `box.info.ro` becomes `true` and start it when it becomes `false`'.

I propose the following API:

```lua
local expirationd = require('expirationd')

expirationd.start(name, space_id, is_tuple_expired, {
    <...>
    when = <function>,  -- process tuples only when this condition is true;
                        -- this may be a user-defined function or a predefined one:
                        -- * `expirationd.has_no_upstreams` (it is default)
                        -- * `expirationd.is_writeable` (usually good for master-master setup)
    force = <boolean>,  -- process tuples despite `opts.when` value
})

--
-- Built-in functions to use in `opts.when`.
--
-- Implementations are listed here to make the idea more clear.
--

expirationd.has_no_upstreams = function()
    -- `replication_source` is the old name of `replication` parameter (prior to 1.7.6).
    -- `box.cfg{replication = {}}` may be used to withdraw from upstreams.
    local upstreams = box.cfg.replication or box.cfg.replication_source
    return upstreams == nil or (type(upstreams) == 'table' and next(upstreams) == nil)
end

expirationd.is_writeable = function()
    -- Not sure whether `box.info.ro` can be `nil` during box configuration.
    -- Consider `nil` as 'read-only' just in case.
    return box.info.ro == false
end
```

The discussion was started in PR #37 by @filonenko-mikhail, then was stale for a long time. I filed the issue to discuss and finally decide what would be most convenient way to configure the module in a multi-instance environment.

**Comment by Totktonada** [comment]
As I see, the condition whether to proceed with tuples is verified in two cases:

* Before traverse a space (the whole space!).
* When a worker fiber is respawned (after an error in `is_tuple_expired()` or `process_expired_tuple()`).

https://github.com/tarantool/expirationd/blob/a700bd18178e25464a0d5a166c344be5ff6b6032/expirationd.lua#L162-L164

I propose to check the `opts.when` function result after each `tuples_per_iteration` tuples for the sake of flexibility. This way we'll able to gracefully stop tuples processing, not only when an expiration operation start to raising errors.

**Comment by Totktonada** [comment]
I would change my proposal a bit now. I don't see much sense in introducing options here. Let's just lean on `box.info.ro` (not `box.cfg.read_only`!) instead of `box.info.replication`. It is technically incompatible change, but at the same time it looks safe enough for real usages.

Details:

* Lean on `box.info.ro`. Stop tasks processing in the read-only state. Start it in the read-write state.
* But! Wait for upstream lag \* 2 before start processing of tasks (to don't hit a conflict due to parallel processing of remaining transactions from the old master and from the new master).
* But! Ignore `box.info.ro` for instance local and temporary spaces (see the table [here](https://www.tarantool.io/en/doc/latest/reference/configuration/#confval-read_only)).
* Keep `force` option just in case (for some very unusual cases).

See https://github.com/tarantool/queue/issues/120#issuecomment-1042810669. We recently solved quite similar problem in the queue module.

**Comment by oleg-jukovec** [comment]
Notes:
1. Replication lag * 2 in queue:
https://github.com/tarantool/queue/blob/ac1a9af96dae9bc1d73a0de52875c45ff361a8b6/queue/abstract/queue_state.lua#L72
2.  `box.info.ro` since 1.7.3, `box.info.server.ro` before.
