### ISSUE TITLE
Document usage scenarios for expirationd, indexpiration and moonwalker

### ISSUE THREAD

**Issue by Totktonada** [tarantool/expirationd#53]
Describe when expirationd, indexpiration and moonwalker are most suitable.

**Comment by ligurio** [comment]
From a conversation with @Mons:

- [moonwalker](https://github.com/tarantool/moonwalker) triggered manually, useful for batch transactions, performance about 600/700k rec/sec
- [expirationd](https://github.com/tarantool/expirationd/issues/53) always expires tuples without using indices but using any condition, without guarantee for time expiration.
- [indexpirationd](https://github.com/moonlibs/indexpiration) always expires tuples with indices, has a nice precision (up to ms) for time to expire.

I propose to add a table with comparison to the README:

| Module        | Expiration time | Uses indices | Trigger              | 
|---------------|-----------------|--------------|----------------------|
| indexpiration | High (ms)       | Yes          | Condition            | 
| expirationd   | Medium (sec)    | No           | Condition            |
| moonwalker    | Low             | No           | Manual (crontab etc) |
