### ISSUE TITLE
Add deploy rpm / deb packages

### ISSUE THREAD

**Issue by ArtDu** [tarantool/expirationd#56]
Build and deploy rpm / deb packages to systems on gh actions, as was done in travis.yml https://github.com/tarantool/expirationd/blob/1.0.1/.travis.yml

**Comment by Totktonada** [comment]
Duplicate of #43.

My bad: I didn't checked, whether it is already exists, and suggested Artem to file an issue regarding deploying of RPM / Deb packages.
