### ISSUE TITLE
show_task_list() should return task list, not print it to the log

### ISSUE THREAD

**Issue by kostja** [tarantool/expirationd#6]
show_task_list() should return task list to the caller. Perhaps rename it to tasks()

**Comment by rtsisyk** [comment]
I suggest to rename API functions:
+--   - expirationd.start_task     -- start a new expiration task => expirationd.start
+--   - expirationd.task_stats     -- show task stats  => expirationd.stats()
 --   - expirationd.task_details   -- show task details =>  => expirationd.details()
+--   - expirationd.kill_task      -- kill a running task  => expirationd.kill
+--   - expirationd.get_task       -- get an existing task  => expirationd.task() (**what the difference between .details() and .stats()**)
+--   - expirationd.get_tasks      -- alias for show_task_list  => expirationd.start  => expirationd.tasks()
+--   - expirationd.show_task_list -- print the task list (use get_tasks instead) => remove
+--   - expirationd.run_task       -- run a new expiration task (obsolete) => run (**what the difference between run and start?**).

**Comment by kostja** [comment]
+1

**Comment by bigbes** [comment]
1) Idea was to save backwards compatibility, so we can have new names, but we need to save old names too.
    * `show_task_list` need to be here
    * `stats` is statistics related functions, `details` are details for started task (not something that user will take for his pretty graphics)
    * add aliases for everything else
2) expirationd.run_task is obsolete (old API, new api is start_task and it differs).
3) All previously `logger` functions may be ported without aliases

**Comment by bigbes** [comment]
@kostja @rtsisyk Is this plan is OK for you?
