### ISSUE TITLE
Add test for space:rename() when expirationd is running on rename space

### ISSUE THREAD

**Issue by no1seman** [tarantool/expirationd#63]
What if expirationd will be runed on some space and that space will be renamed by space:rename? Seems that this case must be tested and fixed if there any misbehavior

**Comment by ligurio** [comment]
The proposed situation is the same as you will destroy your HDD or SSD and then will complain about lost data.
If you want to rename space you will need to set up expirationd again on updated space.

**Comment by no1seman** [comment]
Seems that it's not a problem, if expiration will not work after space:rename or space:drop or space:truncate, but such operations must not lead to crashes or any other poor things if it perfomed on a space with expirationd proceure running on it

**Comment by Totktonada** [comment]
Space renaming can be a part of a migration. A service SLA may impose on-the-fly migrations.

**Comment by oleg-jukovec** [comment]
It seems that we already have tests for this cases:

https://github.com/tarantool/expirationd/blob/b52298fef4b6b092c4db6910ee3c41f11494e7b1/test/unit/space_index_test.lua

So if `space.name` used - a task will stop, if `space.id` the task will continue the execution.
