### ISSUE TITLE
Incorrect description of expiration for replicas

### ISSUE THREAD

**Issue by ArtDu** [tarantool/expirationd#92]
> Note about using expirationd with replication: by default expirationd should process tasks only on the writeable instance, it means that expirationd will not start task processing on a replica. Here the word 'replica' means an instance with at least one configured upstream, it's an option box.cfg.replication_source (box.cfg.replication for Tarantool 1.7.6+)

The expiration seems to behave differently. It will not perform expiration even if the expiration is started on the master. Because if the master is in the replica set, then box.cfg.replication will not be nil. It should be added that expiration will not occur if the instance is included in the replica set, and not specifically on the replica or master.

https://github.com/tarantool/expirationd/blob/513fe16caf31d69882a56b4047cc449927cb3074/expirationd.lua#L151

**Comment by Totktonada** [comment]
Looks connected to #96.
