### ISSUE TITLE
Documentation enhancement

### ISSUE THREAD

**Issue by AnastasMIPT** [tarantool/expirationd#93]
I think it is worth clarifying the description of the installation process by mentioning that you need to install dependencies by adding `make deps` string.

**Comment by ligurio** [comment]
I suspect users don't need to run `make deps` because it installs development rocks like `luatest` and `luacheck`. Runtime dependencies described in rockspec and installed automatically on `tarantoolctl rocks make` or `tarantoolctl rocks install expirationd`.

**Comment by AnastasMIPT** [comment]
If I install `expirationd` by cloning the repository and then run a make test, I get errors about not having a `luatest` command and other errors related to not having dependencies installed.

**Comment by ligurio** [comment]
I still don't get your case. Why do you need to test a local copy of expirationd?
