### ISSUE TITLE
expirationd doesn't process tasks with zero length `box.cfg.replication`

### ISSUE THREAD

**Issue by artemreyt** [tarantool/expirationd#95]
Documentation says  "by default expirationd should process tasks only on the writeable instance, it means that expirationd will not start task processing on a replica. Here the word 'replica' means an instance with at least one configured upstream".

But if to create an instance like:
```lua
box.cfg{
    replication = {};
    read_only = false,
}
```

Expirationd doesn't process tasks. But it has no configured upstream in real.

If it's really a bug, it seems to be because of this line (`box.cfg.replication` actually not nil):
https://github.com/tarantool/expirationd/blob/176e713a4adb3fbe7de448cd891c63ab39e60280/expirationd.lua#L151

Of course option `force` of `expirationd.start()` can help at this case, but In my opinion the word `force` you should use only where it is really needed :)

**Comment by ArtDu** [comment]
also related to #92
