### ISSUE TITLE
something is wrong in documentation

### ISSUE THREAD

**Issue by ligurio** [tarantool/expirationd#96]
> I don't understand a change of "replication_source" (should be just replication, because I don't know projects that use replication_source.

https://github.com/tarantool/expirationd/pull/94

**Comment by Totktonada** [comment]
Looks connected to #92.

**Comment by vlalykin** [comment]
the documentation is incorrect: https://www.tarantool.io/ru/doc/latest/reference/configuration/#cfg-replication-replication

**en**: 
> Since version 1.7.4. **If replication is not an empty string, the instance is considered to be a Tarantool replica**. The replica will try to connect to the master specified in replication with a URI (Universal Resource Identifier)

**ru**: 
> Для версий от 1.7.4. и выше. **Если replication не содержит пустую строку, экземпляр считается репликой**. Реплика попытается подключиться к мастеру, указанному в параметре replication по URI (унифицированному идентификатору ресурса)

this is wrong.

**en**: 
however, in fact, in the cluster, both on the master and on the replica, the value 'replication' **does not contain an empty string** (it contains a list of all members of the replica-set)

**ru**:
на самом деле, в кластере, как на мастере, так и на реплике, значение 'replication' **не содержит пустую строку** (там содержится список всех членов replica-set)

**Comment by vlalykin** [comment]
https://tarantool.github.io/expirationd/

force (boolean, optional)

By default expirationd should process tasks only on the writeable instance, it means that expirationd will not start task processing on a replica. Here the word 'replica' means an instance with at least one configured upstream, it's an option box.cfg.replication_source (box.cfg.replication for Tarantool 1.7.6+). The option force let a user control where to start task processing and where don't.

**ru**:
в кластере, по умолчанию, работа задания в принципе невозможна без принудительного указания `force = true`.
Это происходит потому, что критерий мастер/реплика использует проверку box.cfg.replication == nil, результат которой всегда ложный (там содержится список всех экземпляров шарда независимо от его роли). Если код верный (а мне кажется, что проверка в коде `box.cfg.replication == nil` либо **бессмысленна**, либо нуждается в исправлении), то кажется надо поправить документацию в части опции `force`, а если код неверный, то наверное надо править и код, и документацию.

**Comment by vlalykin** [comment]
https://www.tarantool.io/ru/doc/latest/reference/reference_rock/expirationd/

**en**:
>force (boolean) – run task even on replica. Default: force=false so ordinarily expirationd ignores replicas.

**ru**:
>force (логическое значение) – выполнение задачи даже на реплике. По умолчанию: force=false, поэтому, как правило, expirationd не учитывает реплики.


повторю, что для кластера опция `force `вообще не имеет смысла, если `force==false`, то задание гарантированно не выполняет никакой работы. Определение `force ` некорректно

**Comment by vlalykin** [comment]
> https://www.tarantool.io/ru/doc/latest/reference/reference_rock/expirationd/



> https://www.tarantool.io/ru/doc/latest/reference/reference_rock/expirationd/
> 
> **en**:
> 
> > force (boolean) – run task even on replica. Default: force=false so ordinarily expirationd ignores replicas.
> 
> **ru**:
> 
> > force (логическое значение) – выполнение задачи даже на реплике. По умолчанию: force=false, поэтому, как правило, expirationd не учитывает реплики.

здесь по прежнему не исправлено

**Comment by Totktonada** [comment]
Filed https://github.com/tarantool/doc/issues/2937.
