### ISSUE TITLE
Export metrics from the tasks

### ISSUE THREAD

**Issue by savinov** [tarantool/expirationd#98]
Please export stats() metrics on each storage and add them to Grafana dashboard.
https://tarantool.github.io/expirationd/#stats
https://github.com/tarantool/grafana-dashboard

**Comment by savinov** [comment]
Errors counter would be usefull too.

**Comment by Totktonada** [comment]
I overlooked this issue and we started a discussion of the topic in #100. I propose to track the problem in #100, because of that. If you don't mind, can I close this issue?

**Comment by savinov** [comment]
No problems, go ahead!
